### ISSUE TITLE
Multiple DC replication strategy

### ISSUE THREAD

**Issue by yagnik** [uber/uReplicator#105]
We are trying to run ureplicator across 4 dc's and currently neither mirrormaker nor ureplicator afaik supports replicating everywhere in a way that we don't have duplicate message or infinite chain. 

In order to support such a functionality, we want to add a custom consumer, which reads into the message, finds a "dc" field and if it's different from one in the config of ureplicator then it will replicate. 

Do you think this is something that we can contribute back to ureplicator or how have you solved this issue ?

cc @drdee to get your opinions on this

**Comment by xhl1988** [comment]
@yagnik Thanks for reaching out to us. This is a very useful feature and welcome to contribute to uReplicator.

**Comment by yagnik** [comment]
We are trying out replicator by confluent for now but keeping an eye out for this. Will revert if we get somewhere :)
thanks @xhl1988

**Comment by xhl1988** [comment]
Hi, @yagnik , we are also facing the situation which required replication filtering and we found a simple solution to filter this in producer (https://github.com/uber/uReplicator/pull/132/files). It's quite difficult to filter the message on the consumer side which caused a lot of memory and cpu overhead during our test. Lemme know if you have any thoughts or suggestion.
