### ISSUE TITLE
Is Federated-uReplicator branch usable?

### ISSUE THREAD

**Issue by ct16k** [uber/uReplicator#121]
I'd like to evaluate uReplicator as a replacement for the 'default' MirrorMaker that we're currently using in prod. Which branch do you recommend, should I start with `Federated-uReplicator` to take advantage of upcoming features, or is it still WIP/too unstable and I should stick with `master` ?

**Comment by xhl1988** [comment]
Hi @ct16k , Federated-uReplicator is still under test. We are in the process to productize Federated uReplicator. For now, please use the master branch.

**Comment by ct16k** [comment]
Thank you!
