### ISSUE TITLE
Federated uReplicator?

### ISSUE THREAD

**Issue by balboah** [uber/uReplicator#125]
While looking for metrics to use for monitoring lagging replication, I noticed the offset monitor which seem to only exist in Federated uReplicator branch.
Is this branch something usable and why are these features not merged back into master?

Appreciate pointers to which metrics that are most useful for monitoring replication status

@xhl1988

**Comment by xhl1988** [comment]
We are still testing Federated uReplicator in our staging environment. After we migrate to Federated uReplicator, we will merge it back to master.

In our experience, the most important ones are MaxLag on worker side and NumNoProgressPartitions on controller side. Other metrics like BytesPerSec from Producer/Consumer itself are also very useful.

**Comment by balboah** [comment]
thanks for the update, appreciated

**Comment by dungnt081191** [comment]
Hi @xhl1988  , at this time , Federated uReplicator mode is working or not ? 
Do you have any document for this mode ?

**Comment by xhl1988** [comment]
@dungnt081191 federation mode is working and we are using it in production. You can find the user guide [here](https://github.com/uber/uReplicator/wiki/uReplicator-User-Guide) and meetup talk [here](https://www.youtube.com/watch?v=T2RDH0v3pzs).

**Comment by dungnt081191** [comment]
Hi @xhl1988  , do you have clear introduction about federation mode ? 
on README.md just have a few information about it ?
