### ISSUE TITLE
[question] Topic Mapping and rewrite rules

### ISSUE THREAD

**Issue by svart-ravn** [uber/uReplicator#152]
Hello,

On a source cluster I have several topics matched by some regexp pattern. Is it possible make uReplicator to push messages from them to a single topic on a destination cluster?
As far as I understood from the code you do not support this. Is there any chance that you can implement a kind of "rewrite rules" based on regexp?

thanks

**Comment by xhl1988** [comment]
Currently we don't have plan to implement this. But if you want to support this, you can submit a PR and we will be happy to review and merge it.

**Comment by svart-ravn** [comment]
Thank you for your reply.
