### ISSUE TITLE
Question : Can't workout -enableAutoWhitelist setting

### ISSUE THREAD

**Issue by ksambhav** [uber/uReplicator#18]
I am trying to workout a setup with following configuration on a single local machine : -

```
Zookeeper - 3 isolated instances ( NOT in one ensemble).
	- 1 for helix cluster. 		port 2181
	- 1 for source kafka   		port 2182
	- 1 for destication Kafka          port 2183

Kafka - 2 instances ( 1 broker in each)
	-   1 As source kafka 		port 9092, zk-port 2182
	-   1 As destination Kafka        port 9093, zk-port 2183
```

**helix.properties** - 

```
zkServer=localhost:2181
instanceId=testHelixMirrorMaker01
helixClusterName=testMirrorMaker
```

**consumser.properties**

```
zookeeper.connect=127.0.0.1:2182 // zk instance for source kafka
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000
group.id=kloak-mirrormaker-test
consumer.id=kloakmms01-sjc1
partition.assignment.strategy=roundrobin
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=8388608
queued.max.message.chunks=5
auto.offset.reset=smallest
```

**producer.properties**

```
bootstrap.servers=localhost:9093 // destination kafka instance.
client.id=kloak-mirrormaker-test
producer.type=async
compression.codec=none
serializer.class=kafka.serializer.DefaultEncoder
key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
```

**uReplicator Controller run arguments**:-
`startMirrorMakerController -helixClusterName testMirrorMaker -zookeeper localhost:2181 -port 9000 -mode auto -srcKafkaZkPath localhost:2182 -destKafkaZkPath localhost:2183 -enableAutoWhitelist true -autoRebalanceDelayInSeconds 120 -backUpToGit false -localBackupFilePath D:/sambhav/tmp/localBackup`

**uReplicator worker run argument**
`startMirrorMakerWorker --consumer.config D:/sambhav/projects/github/uReplicator/config/consumer.properties --producer.config D:/sambhav/projects/github/uReplicator/config/producer.properties --helix.config D:/sambhav/projects/github/uReplicator/config/helix.properties`

Questions:-

1.  Should there be a dedicated zk ensemble for helix-cluster or I should share the zk ensemble used by source-kafka|destination kafka ? What is right | recommnded way ?

2. After running above mentioned components, I am able to replicate topics only after hitting POST http://localhost:9000/topics endpoint. 'enableAutoWhitelist' seems to be not working me. What am I missing here ? I wan't all topics in my source kafka cluster to be replicated to destination cluster.

Thanks.

**Comment by xhl1988** [comment]
@ksambhav sorry for the late reply. Does it work now?
1. zk can be shared. However, I noticed that the zookeeper.connect in consumser.properties didn't include the zk path, e.g. zookeeper.connect=127.0.0.1:2181/cluster1, which might cause problems.
2. How long did you wait for the auto-whitelist? Have you created the same topics in destination  cluster? (If a topic is in both source and destination Kafka clusters, the controller auto-whitelists the topic and starts copying data.)

**Comment by ksambhav** [comment]
@xhl1988 Yes I am to work it out now. Thanks !
