### ISSUE TITLE
Compatibility with  0.10 or 0.11 kafka 

### ISSUE THREAD

**Issue by ravi45722** [uber/uReplicator#20]
Presently we are using the uReplicator with 0.9 kafka version. I want to upgrade my kafka to 0.10 or above. Is this uReplicator compatible with those kafka versions???

**Comment by ksambhav** [comment]
You can find that in https://github.com/liangyc/uReplicator fork.

**Comment by ravi45722** [comment]
This repository will work with 0.10 version or 0.11. Can you please specify??

**Comment by ksambhav** [comment]
0.10 , there will be different branch in this fork

**Comment by ravi45722** [comment]
https://github.com/liangyc/uReplicator/tree/kfk0.10

Is this the branch you are saying???

**Comment by xhl1988** [comment]
@ravi45722 It is compatible with 0.10 or 0.11 kafka.
