### ISSUE TITLE
Please share the command/instructions to delete the uReplicator worker instances in helix.

### ISSUE THREAD

**Issue by SrinivasRaoMallampati** [uber/uReplicator#211]

**Comment by xhl1988** [comment]
@SrinivasRaoMallampati You can blacklist a worker by `curl -X DELETE <controller>:<port>/instances/<worker>`. It's just blacklisting the host so no partition will be assigned to the host. Or you can simply shutdown the worker.

**Comment by SrinivasRaoMallampati** [comment]
Thank you.

How can i view all the worker instances add in Helix Controller before deleting them?

**Comment by xhl1988** [comment]
`curl <controller>:<port>/instances/<worker>`
