### ISSUE TITLE
Replicating access control list (ACLs)

### ISSUE THREAD

**Issue by PrashantSabnekar** [uber/uReplicator#217]
I want to know whether uReplicator replicates access control list of topics. Mirror Maker does not replicate it.

In Mirror Maker, lets say we have two data centers (Clusters)  DC1 and DC2 here when we create a topic in one data center the topic gets also created in the other data center and when data is pushed into the topic then the data also gets replicated to the other data center but the access control list of that topics do not get applied to the destination data center. 

I was just curious to know if this tool can help us also replicate ACLs. 

Please Help.

**Comment by yangy0000** [comment]
uReplicator don't replicating ACLs.

**Comment by PrashantSabnekar** [comment]
Thanks for the confirmation Yang.
