### ISSUE TITLE
How to setup uReplicator for fault tolerance and high availability

### ISSUE THREAD

**Issue by cszczotka** [uber/uReplicator#218]
Hi,
Do you have any recommendation how setup the uReplicator for fault tolerance and high availability ? Will be enough have two - three instances of controller and few instances of worker running on separate host/box ? What is the purpose of uReplicator-Manager ? 
Thanks,

**Comment by xhl1988** [comment]
1. For fault tolerance and high availability, 3 controller and few instances should be enough. You can calculate the total workload of the topics and estimate the number of workers with a few spares.

2. uReplicator-Manager is a federation layer on top of the uReplicator setup (controller+worker). We developed this as we have too many uReplicator (controller+worker) deployments and uReplicator-Manager helps us manage the deployments automatically.
