### ISSUE TITLE
how can i verify uReplicator is 1-1 Partition Mapping replicator

### ISSUE THREAD

**Issue by wk909005** [uber/uReplicator#219]
i have tested uReplicator ,but is seems not 1-1 partiton replicator,src kafka and des kafka  message distribute is not the same.
<[appdeploy@cnsz22VLK12969:/home/appdeploy/kafka_2.12-0.10.2.2/bin]$sh kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 10.203.168.132:9098 --topic wktest05 --time -1
wktest05:8:490
wktest05:2:490
wktest05:5:490
wktest05:4:490
wktest05:7:490
wktest05:1:490
wktest05:9:491
wktest05:3:491
wktest05:6:492
wktest05:0:491
[appdeploy@cnsz22VLK12969:/home/appdeploy/kafka_2.12-0.10.2.2/bin]$sh kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 10.203.168.139:9098 --topic wktest05 --time -1
wktest05:8:491
wktest05:2:491
wktest05:5:490
wktest05:4:490
wktest05:7:490
wktest05:1:490
wktest05:9:490
wktest05:3:491
wktest05:6:491
wktest05:0:491
>

**Comment by xhl1988** [comment]
What's your worker start command?

**Comment by wk909005** [comment]
OK,here is my conmands；
controller command: nohup ./bin/start-controller.sh -port 9000 -helixClusterName testMirrorMaker -zookeeper 10.203.168.132:2181 -enableAutoWhitelist true -srcKafkaZkPath 10.203.168.132:2181/kafka/test01 -destKafkaZkPath 10.203.168.139:2181/kafka/test02 > controller.log 2>&1 &
work conmmand: nohup ./bin/start-worker.sh --consumer.config ./config/consumer.properties --producer.config ./config/producer.properties --helix.config ./config/helix.properties > worker.log 2>&1 &
thses properties as follows:
<[appdeploy@cnsz22VLK12969:/home/appdeploy/uReplicator-master/uReplicator-Distribution/target/uReplicator-Distribution-pkg/config]$grep -v \# consumer.properties | grep -v '^$'
zookeeper.connect=10.203.168.132:2181/kafka/test01
zookeeper.connection.timeout.ms=30000
zookeeper.session.timeout.ms=30000
group.id=kloak-mirrormaker-test
consumer.id=kloakmms01-sjc1
partition.assignment.strategy=roundrobin
socket.receive.buffer.bytes=1048576
fetch.message.max.bytes=8388608
queued.max.message.chunks=5
auto.offset.reset=smallest
[appdeploy@cnsz22VLK12969:/home/appdeploy/uReplicator-master/uReplicator-Distribution/target/uReplicator-Distribution-pkg/config]$grep -v \# producer.properties | grep -v '^$'
bootstrap.servers=10.203.168.139:9098,10.203.168.140:9098,10.203.168.141:9098
client.id=kloak-mirrormaker-test
producer.type=async
compression.type=none
key.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
value.serializer=org.apache.kafka.common.serialization.ByteArraySerializer
[appdeploy@cnsz22VLK12969:/home/appdeploy/uReplicator-master/uReplicator-Distribution/target/uReplicator-Distribution-pkg/config]$grep -v \# helix.properties | grep -v '^$'
 zkServer=localhost:2181
 instanceId=testHelixMirrorMaker01
 helixClusterName=testMirrorMaker
>

**Comment by wk909005** [comment]
Please tell me how to implement 1-1 Partition Mapping replicator ;Thanks a lot!!

**Comment by xhl1988** [comment]
When you start worker, you need an extra option `--dstzk.config dstzk.properties`. Content of that file is just `enable=true`.

**Comment by wk909005** [comment]
I have added the extra option --dstzk.config dstzk.properties when i started the worker;and i tested again,it seems not to work,Number of messages per partition is not the same between the src and dst:
<sh kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 10.203.168.132:9098 --topic wktest09 --time -1
wktest09:8:191
wktest09:2:191
wktest09:5:190
wktest09:4:190
wktest09:7:190
wktest09:1:190
wktest09:9:190
wktest09:3:191
wktest09:6:192
wktest09:0:192
$sh kafka-run-class.sh kafka.tools.GetOffsetShell --broker-list 10.203.168.139:9098 --topic wktest09 --time -1
wktest09:8:190
wktest09:2:190
wktest09:5:190
wktest09:4:191
wktest09:7:191
wktest09:1:191
wktest09:9:191
wktest09:3:191
wktest09:6:191
wktest09:0:191>
the conent of the dstzk.properties:
<cat config/dstzk.properties 
enable=true>

**Comment by xhl1988** [comment]
Sorry, dstzk.properties needs another line:
```
enable=true
zkServer=<dst zk path>
```
zkServer is the zk path your broker uses.

**Comment by wk909005** [comment]
Nice,it's well done. Thank u very much! but i still have two questions:
1,Why does the number of synchronized partitions change while I do nothing,I set it to 5, but after a while it becomes 10:
<curl -X POST -d '{"topic":"wktest10", "numPartitions":"5"}' http://localhost:9000/topics
curl http://localhost:9000/topics/wktest10
{"externalView":{"0":["testHelixMirrorMaker01"],"1":["testHelixMirrorMaker01"],"2":["testHelixMirrorMaker01"],"3":["testHelixMirrorMaker01"],"4":["testHelixMirrorMaker01"]},"idealState":{"0":["testHelixMirrorMaker01"],"1":["testHelixMirrorMaker01"],"2":["testHelixMirrorMaker01"],"3":["testHelixMirrorMaker01"],"4":["testHelixMirrorMaker01"]},"serverToNumPartitionsMapping":{"testHelixMirrorMaker01":5},"serverToPartitionMapping":{"testHelixMirrorMaker01":["0","1","2","3","4"]},"topic":"wktest10"}
curl http://localhost:9000/topics/wktest10
{"externalView":{"0":["testHelixMirrorMaker01"],"1":["testHelixMirrorMaker01"],"2":["testHelixMirrorMaker01"],"3":["testHelixMirrorMaker01"],"4":["testHelixMirrorMaker01"],"5":["testHelixMirrorMaker01"],"6":["testHelixMirrorMaker01"],"7":["testHelixMirrorMaker01"],"8":["testHelixMirrorMaker01"],"9":["testHelixMirrorMaker01"]},"idealState":{"0":["testHelixMirrorMaker01"],"1":["testHelixMirrorMaker01"],"2":["testHelixMirrorMaker01"],"3":["testHelixMirrorMaker01"],"4":["testHelixMirrorMaker01"],"5":["testHelixMirrorMaker01"],"6":["testHelixMirrorMaker01"],"7":["testHelixMirrorMaker01"],"8":["testHelixMirrorMaker01"],"9":["testHelixMirrorMaker01"]},"serverToNumPartitionsMapping":{"testHelixMirrorMaker01":10},"serverToPartitionMapping":{"testHelixMirrorMaker01":["0","1","2","3","4","5","6","7","8","9"]},"topic":"wktest10"}
>
2.How to query the synchronous state? Is there any monitoring method?    Looking forward to your reply. Thank you again!

**Comment by xhl1988** [comment]
1. How many partitions are in source cluster? You enabled `
-enableAutoWhitelist true`, so controller will auto whitelist the missing partitions.

2. What do you mean by "synchronous state"?

**Comment by wk909005** [comment]
Thank you for your reply;
1. there are 10 partitions in source cluster.
2.I mean how do you monitor replication from source cluster to destination cluster;Any tools here?

**Comment by xhl1988** [comment]
1. In this case, `-enableAutoWhitelist true` will auto whitelist the remaining 5 partitions.

2. You can add `-javaagent:./bin/libs/jmxtrans-agent-1.2.4.jar=config/jmxtrans.xml` and check the metrics in jmxtrans.xml. Please see the `uReplicator-Worker/README.md` after we merge #220. We will add instructions for controller later.

**Comment by wk909005** [comment]
thank U,I see.

**Comment by wk909005** [comment]
hello,I have one more question,Does uReplicatou support kafka_2.10-0.8.2.1?At first, the source cluster and target cluster I tested were both 0.8 version, but failed; Is there a  kafka version requirement for uReplicator?What is the minimum required  kafka version of Ureplicator? Looking forward to your reply. Thank you again!

**Comment by yangy0000** [comment]
Please try kafka-0.8.2.1 branch.

**Comment by wk909005** [comment]
hello,Is there a difference between kafka-0.8.2.1 branch and  master ? When I use kafka 0.8.2.1 branch, it doesn't seem to replicator successfully; The worker and controller start command are the same as before.

**Comment by wk909005** [comment]
here are errors:
1、start controller error:
2019-03-06T20:40:58.020+0800: Total time for which application threads were stopped: 0.0005317 seconds, Stopping threads took: 0.0000629 seconds
2019-03-06T20:40:58.146+0800: Total time for which application threads were stopped: 0.0005706 seconds, Stopping threads took: 0.0002429 seconds
[2019-03-06 20:40:58,159] ERROR Error writing backup to the file idealState-backup-env (com.uber.stream.kafka.mirrormaker.controller.core.FileBackUpHandler:49)
[2019-03-06 20:40:58,159] ERROR Failed to take backup, with exception: java.lang.NullPointerException (com.uber.stream.kafka.mirrormaker.controller.core.ClusterInfoBackupManager:72)

2.start work with the option --dstzk.config ./config/dstzk.properties error:
[2019-03-06T18:50:42.271+0800: Total time for which application threads were stopped: 0.0124421 seconds, Stopping threads took: 0.0000455 seconds
[2019-03-06 18:50:42,347] INFO Starting mirror maker (kafka.mirrormaker.MirrorMakerWorker$:68)
Exception in thread "main" joptsimple.UnrecognizedOptionException: 'dstzk.config' is not a recognized option
	at joptsimple.OptionException.unrecognizedOption(OptionException.java:93)
	at joptsimple.OptionParser.handleLongOptionToken(OptionParser.java:402)
	at joptsimple.OptionParserState$2.handleArgument(OptionParserState.java:55)
	at joptsimple.OptionParser.parse(OptionParser.java:392)
	at kafka.mirrormaker.MirrorMakerWorker$.main(MirrorMakerWorker.scala:126)
	at kafka.mirrormaker.MirrorMakerWorker.main(MirrorMakerWorker.scala)
	at com.uber.stream.kafka.mirrormaker.starter.MirrorMakerStarter.main(MirrorMakerStarter.java:45)
3 start work without --option --dstzk.config ./config/dstzk.properties error:
19-03-06T20:43:44.392+0800: Total time for which application threads were stopped: 0.0003483 seconds, Stopping threads took: 0.0000616 seconds
kafka.consumer.ConsumerTimeoutException
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:69)
	at kafka.consumer.ConsumerIterator.makeNext(ConsumerIterator.scala:33)
	at kafka.utils.IteratorTemplate.maybeComputeNext(IteratorTemplate.scala:66)
	at kafka.utils.IteratorTemplate.hasNext(IteratorTemplate.scala:58)
	at kafka.mirrormaker.MirrorMakerWorker$MirrorMakerThread.run(MirrorMakerWorker.scala:303)

**Comment by wk909005** [comment]
OK，i have  implemented replicator through branch kafka-0.8.2.1;But it doesn't support  the option --dstzk.config;so it's NOT 1-1 Partition Mapping replicator; how solve this? Looking forward to your reply. Thank you again!

**Comment by xhl1988** [comment]
Do you need 1-1 partition mapping? It's fine to replicate without 1-1 mapping. We don't support that in 0.8.2.1 branch. If you want that, you can try to patch the diff.

**Comment by yangy0000** [comment]
Here is the diff for 1-1 mapping

https://github.com/uber/uReplicator/commit/e3e4e46462bda28895e2e2b80aa7fd70b7ae83db#diff-09d062719a93718d910837ffcd461991

I can try to make a patch over the weekend, but there is no guarantee.

**Comment by wk909005** [comment]
Thank you for your answers. Yes, we need  1-1 partition mapping.I'll try to patch the diff,But this should be difficult for me because I'm not a developer.

**Comment by yangy0000** [comment]
https://github.com/uber/uReplicator/commit/e3e4e46462bda28895e2e2b80aa7fd70b7ae83db#diff-09d062719a93718d910837ffcd461991

**Comment by yangy0000** [comment]
https://github.com/uber/uReplicator/pull/222
