### ISSUE TITLE
uReplicator front

### ISSUE THREAD

**Issue by gpicron** [uber/uReplicator#233]
Hi, I'm currently evaluating uReplicator.   During your presentation (https://www.youtube.com/watch?v=T2RDH0v3pzs) you introduced the "front" component which i don't find in the github repo.

Else, let me thanks all the team for this excellent work.  When the doc will be at the level of the engineering there will be no point to develop MM2.

**Comment by yangy0000** [comment]
@xhl1988  He is currently working on the documentation backfill.

**Comment by xhl1988** [comment]
@gpicron We didn't open source uReplicator Front as it contains some internal code; However, the main purpose of Front is to find the correct uReplicator Manager for you so you don't really need it if you don't have too many Manager deployments or you can use a script to replace Front.
