### ISSUE TITLE
Why consumer offsets message stored  on ZK?

### ISSUE THREAD

**Issue by fulin87** [uber/uReplicator#246]
As we know that now kafka stored consumer offsets message on brokers. And Client can get the offsets information very easily from the brokers。
What's the reason for uReplicator store its consumer offsets on ZK ? 
Does users can choose where to store the offsets message ?

**Comment by Technoboy-** [comment]
i think, this is because uReplicator is developped too early and that time kafka stores offset in zk and including some consumer or producer properties is deprecated now
later updates will support to store on broker maybe
