### ISSUE TITLE
Bump up kafka dependency to 0.10.x

### ISSUE THREAD

**Issue by eschizoid** [uber/uReplicator#25]

**Comment by xhl1988** [comment]
We will address this as well as other dependencies later.

**Comment by ksambhav** [comment]
There are few forks where it's already done : - 

One I found good for starting point : -
https://github.com/liangyc/uReplicator/tree/kfk0.10

**Comment by xhl1988** [comment]
#27 #

**Comment by xhl1988** [comment]
@eschizoid @ksambhav Already merged #27 . Please try it out.

**Comment by xhl1988** [comment]
Upgraded to 0.10.2.1 in #30
