### ISSUE TITLE
What's the difference between the two directories    for  uReplicator-Worker-3.0   and  uReplicator-Worker  ?

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#260]
What's the difference between the two directories  
 for  uReplicator-Worker-3.0   and  uReplicator-Worker  ?

**Comment by Technoboy-** [comment]
uReplicator-Worker-3.0 writes in Java as uReplicator-Worker is in Scala

**Comment by Bruce2jiang** [comment]
Where to download binary package ?

**Comment by Technoboy-** [comment]
download the source code from master branch and build with "mvn clean package"

**Comment by Technoboy-** [comment]
or "mvn clean package -DskipTests=true"

**Comment by Bruce2jiang** [comment]
[yunwei@UAT-HADOOP-06 uReplicator]$ bin/grid bootstrap
: invalid option

**Comment by yangy0000** [comment]
uReplicator-Worker-3.0 uses Kafka consumer 1.1.0 which supports kafka security feature. However uReplicator-Worker uses deprecated simple consumer.
We plan to deprecated "uReplicator-Worker" from the long term.
