### ISSUE TITLE
[INFO] uReplicator-Controller ............................. FAILURE [03:17 min]

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#266]
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO] 
[INFO] uReplicator ........................................ SUCCESS [ 10.991 s]
[INFO] uReplicator-Common ................................. SUCCESS [ 29.406 s]
[INFO] uReplicator-Controller ............................. FAILURE [03:17 min]
[INFO] uReplicator-Worker ................................. SKIPPED
[INFO] uReplicator-Manager ................................ SKIPPED
[INFO] uReplicator-Distribution ........................... SKIPPED
[INFO] uReplicator-Worker-3.0 ............................. SKIPPED
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 03:58 min
[INFO] Finished at: 2019-09-18T09:26:53+08:00
[INFO] Final Memory: 24M/775M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project uReplicator-Controller: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\uber\uReplicator\uReplicator\uReplicator-Controller\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :uReplicator-Controller

Process finished with exit code 1

**Comment by Technoboy-** [comment]
as add the dependancies of jetty-util,jetty-io, please update the version of restlet.version to 2.3.0 and jetty.version to 9.2.6.v20141205

**Comment by Bruce2jiang** [comment]
[INFO] 
[INFO] uReplicator ........................................ SUCCESS [ 14.157 s]
[INFO] uReplicator-Common ................................. SUCCESS [ 25.218 s]
[INFO] uReplicator-Controller ............................. SUCCESS [03:48 min]
[INFO] uReplicator-Worker ................................. SUCCESS [ 39.071 s]
[INFO] uReplicator-Manager ................................ SUCCESS [01:13 min]
[INFO] uReplicator-Distribution ........................... SUCCESS [  8.254 s]
[INFO] uReplicator-Worker-3.0 ............................. FAILURE [01:26 min]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 07:54 min
[INFO] Finished at: 2019-09-18T10:16:05+08:00
[INFO] Final Memory: 255M/1142M
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.14:test (default-test) on project uReplicator-Worker-3.0: There are test failures.
[ERROR] 
[ERROR] Please refer to D:\uber\uReplicator\uReplicator\uReplicator-Worker-3.0\target\surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <goals> -rf :uReplicator-Worker-3.0

Process finished with exit code 1

**Comment by Technoboy-** [comment]
how about build it with -DskipTests=true

**Comment by Bruce2jiang** [comment]
Can I use   "uReplicator-Worker"instead of this  "uReplicator-Worker-3.0"?

**Comment by Technoboy-** [comment]
> Can I use "uReplicator-Worker"instead of this "uReplicator-Worker-3.0"?

yes, depends on you
