### ISSUE TITLE
work error

### ISSUE THREAD

**Issue by Bruce2jiang** [uber/uReplicator#268]
Error: Main method is not static in class kafka.mirrormaker.MirrorMakerWorker, please define the main method as:
   public static void main(String[] args)
Heap
 garbage-first heap   total 5242880K, used 2048K [0x0000000680000000, 0x0000000680205000, 0x00000007c0000000)
  region size 2048K, 2 young (4096K), 0 survivors (0K)
 Metaspace       used 3437K, capacity 4792K, committed 5120K, reserved 1056768K
  class space    used 338K, capacity 424K, committed 512K, reserved 1048576K

**Comment by Technoboy-** [comment]
new MirrorMakerWorker().main(args);

**Comment by yangy0000** [comment]
Please attached your startup coomand
