### ISSUE TITLE
controllerPort option was removed in Manager Module ?

### ISSUE THREAD

**Issue by xinzhuxiansheng** [uber/uReplicator#289]
I packaged code from the latest mater branch  and followed  the start command from the wiki manager config ,but  failed  . It showed that ControllerPort option does not exist.  :smile:

**Comment by Technoboy-** [comment]
yes, you don't need to specify the controller port in manager anymore。but still have to specify in controller. for uReplicator will store these info in Helix. so it's more convenience for user, right ?

**Comment by xinzhuxiansheng** [comment]
yes,I get it, Thanks
