### ISSUE TITLE
Intermittent Stoppage of CompactConsumerFetcherThread

### ISSUE THREAD

**Issue by steve-tr** [uber/uReplicator#29]
We have been experiencing an intermittent shutdown of the CompactConsumerFetcherThread(s) in our production environment. We can restart the workers to get things working again, but eventually uReplicator gets into a state where we can use 'jconsole' to observe that there are no running CompactConsumerFetcherThread instances.

DEBUG logging has not given us any additional information, and we have not been able to reliably replicate this.

Has anyone seen this or similar behavior before, and if so, do you have any details about what we could do to eliminate or even mitigate this problem?

**Comment by xhl1988** [comment]
@steve-tr If the CompactConsumerFetcherThread went down due to some exception, there should be an error log "error("Error due to ", e)" from ShutdownableThread class. Could you please check if you get any log like that?
