### ISSUE TITLE
Consumer  client.id is named ureplicator-null-null-null-1 

### ISSUE THREAD

**Issue by xinzhuxiansheng** [uber/uReplicator#294]
I debuged  the module which is Work-3.0 and found the name of client.id in console logging，It is strange .

2019-11-07 18:51:03  [ org.apache.kafka.common.config.AbstractConfig:279 ] - [ INFO ]  ConsumerConfig values: 
	auto.commit.interval.ms = 5000
	auto.offset.reset = latest
	bootstrap.servers = [vm01.com:9093]
	check.crcs = true
	client.id = ureplicator-null-null-null-1
	connections.max.idle.ms = 540000
	enable.auto.commit = false
	exclude.internal.topics = true
...

Here is the code:
com/uber/stream/ureplicator/worker/WorkerInstance.java:128
String clientId = String.format("ureplicator-%s-%s-%s", srcCluster, dstCluster, routeId);

com/uber/stream/ureplicator/worker/WorkerStarter.java:82
controllerWorkerHelixHandler = new ControllerWorkerHelixHandler(helixProps,
            helixClusterName, workerInstance);

com/uber/stream/ureplicator/worker/WorkerConf.java:303
public static Options constructWorkerOptions() {
    final Options workerOptions = new Options();
    workerOptions.addOption("help", false, "Help")
        .addOption(FEDERATED_ENABLED, true, "Whether to enable federated uReplicator")
        .addOption(CONSUMER_CONFIG_FILE, true,
            "Embedded consumer config for consuming from the source cluster.")
        .addOption(PRODUCER_CONFIG_FILE, true, "Embedded producer config.")
        .addOption(HELIX_CONFIG_FILE, true, "Embedded helix config.")
        .addOption(CLUSTER_CONFIG_FILE, true, "Embedded cluster config.")
        .addOption(TOPIC_MAPPING_FILE, true,
            "Path to file containing line deliminated mappings of topics to consume from and produce to.")
        .addOption(ENABLE_TOPIC_PARTITION_COUNT_OBSERVER, true,
            "Configure the uReplicator to observe destination topic partition count")
        .addOption(OFFSET_COMMIT_INTERVAL_MS, true, "Offset commit interval in ms")
        .addOption(ABORT_ON_SEND_FAILURE, true, "Configure the uReplicator exit on a failed send.")
        .addOption(ENABLE_FILTER, true,
            "Configure the uReplicator to filter message to send to dst cluster.")
        .addOption(HOSTNAME, true,
            "hostname for this host")
        .addOption(REGION, true,
            "region for worker instance")
        .addOption(METRICS_PREFIX, true,
            "metrics prefix")
        .addOption(GRAPHITE_HOST, true, "graphite host")
        .addOption(GRAPHITE_PORT, true, "graphite port")
        //
        .addOption(GRAPHITE_REPORT_FREQ_IN_SEC, true, "graphite report frequency in seconds")
        .addOption(ENABLE_JMX_REPORT, true, "enable jmx report")
        .addOption(ENABLE_GRAPHITE_REPORT, true, "enable graphite report")
        //
        .addOption(WORKER_PORT, true, "worker port");
    return workerOptions;
  }

How to get these value if these are not defined in options ， It's better to make it more evident for people to understand according to the definition.

**Comment by xhl1988** [comment]
What's your config for worker?

**Comment by Technoboy-** [comment]
looks like a bug,  we will comment after discussing

**Comment by xinzhuxiansheng** [comment]
@Technoboy-  I cannot clearly understand the  ConsumerFetcherThread Constructor (this.kafkaConsumer = new KafkaConsumer(properties)),   Serialization in kafkaconsumer configurations parameter are key.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer and value.deserializer=org.apache.kafka.common.serialization.ByteArrayDeserializer .

I created a producer to write data，the configured serialization parameters are
properties.put("key.serializer", "org.apache.kafka.common.serialization.StringSerializer");
properties.put("value.serializer", "org.apache.kafka.common.serialization.StringSerializer");

I don't quite understand why ureplicator consumers can poll data, Their serialization is different.
producer  StringSerializer   -->  consumer  ByteArrayDeserializer 

I hope you can understant what i mean.  I'm looking forward for your reply.

**Comment by Technoboy-** [comment]
all the data will be transport via byte array, right ?
so ,if producer uses StringSerializer, the underlayer channel(socket) will make it to byte array with easy way like : String.getBytes("UTF-8");
and consumer uses ByteArrayDeserializer , but consumer does not known what the byte array mean, what the byte array can deserialize  to Json, to xml, to Object and etc. so producer and consumer have to negotiate before producing message and deserialize message.
you know that all the storage store data via byte array.

**Comment by xinzhuxiansheng** [comment]
Thank you for solving my doubts.  I forgot the relationship between the generics of kafkaconsumer and serialization.

**Comment by Technoboy-** [comment]
reference to https://github.com/uber/uReplicator/pull/296
@xinzhuxiansheng
