### ISSUE TITLE
uReplicator does not delete the unlive instance

### ISSUE THREAD

**Issue by Technoboy-** [uber/uReplicator#298]
when restart workers in docker, below list has some unlive instances
```
[zk: platform-ureplicator-zk:2184(CONNECTED) 21] ls /controller-worker-cluster2-cluster1-0/INSTANCES
[10.221.77.149, 10.221.69.210, 10.221.56.100, 10.221.24.75, 10.221.67.134, 10.221.48.33, 10.221.62.230, 10.221.7.228, 10.221.84.32, 10.221.65.75]
```

**Comment by dungnt081191** [comment]
confirm this happen in K8s my deployment , but in Controller . 
When start - Controller list out all instance which connected with. 
All - i mean the list included old instance which terminated long time  ago .

**Comment by Technoboy-** [comment]
we will discuss if it is the Helix bug.
but, take a look at my new pr , that will resolve the controller registry with ip instead of hostname.
if you use federate mode, controller will register itself using hostname that will result manager can not request to it via http

**Comment by yangy0000** [comment]
this is expected as Live Instances are stored under /LIVEINSTANCES path.
