### ISSUE TITLE
Kafka 0.8.2 support?

### ISSUE THREAD

**Issue by manupkd** [uber/uReplicator#305]
Hello,

Does uReplicator supports Kafka 0.8.2 version?
We have a Kafka cluster which is having older Kafka version 2.10_0.8.2.1. We are planning to migrate to new Confluent version confluent-kafka-2.12-5.4.0. Can we use uReplicator for replicating from this old version to newer version

**Comment by yangy0000** [comment]
There is a branch kafka-0.8.2.1 supports consumer and produce to kafka 0.8.2.1, for produce on `confluent-kafka-2.12-5.4.0`, no one tested it before.

**Comment by manupkd** [comment]
Thank you @yangy0000 ! We were able to deploy uReplicator with kafka-0.8.2.1 branch for consuming from 0.8.2.1 and produce it to new conflent kafka version.
