### ISSUE TITLE
关于ureplicator 非联邦 模式的性能问题

### ISSUE THREAD

**Issue by soraka-hu** [uber/uReplicator#319]
Hi:

I have an urgent question to enquire.
My question is about the perfomance of ureplicator. Currently, ureplicators are installed on 3 machines, called master01, master02 and master03 separaterly. The controller roles are started on master01 and master02, and all of the three machines start worker roles.

The speed of copying data within kafka is 3, 000, 000/min, while my goal is around 10, 000, 000/min. If another worker role is added, the speed would be up to 4, 000, 000 per minute.

Since the management cost would be increased when adding more workers here, I wonder if there is any way (setting\optimize) can improve the speed of the task without adding any new worker.

Images below are my settings. The code I used is from branch 0.1.
 

![image](https://user-images.githubusercontent.com/72863256/95996850-b7055d80-0e65-11eb-9fcc-47b45f03c72e.png)

![image](https://user-images.githubusercontent.com/72863256/95996983-de5c2a80-0e65-11eb-8ab3-f85b2b33bb55.png)

The command to start the role is:    

**controller**

![image](https://user-images.githubusercontent.com/72863256/95997139-0f3c5f80-0e66-11eb-9d30-63014e8ec189.png)
       **worker**
![image](https://user-images.githubusercontent.com/72863256/95997227-2a0ed400-0e66-11eb-9f39-1a9cf7a7c65d.png)

The jvm optimization of the script to start worker role is:
![image](https://user-images.githubusercontent.com/72863256/95997422-57f41880-0e66-11eb-95c6-3060f529d4f7.png)

**Comment by yangy0000** [comment]
1: what is your TCP round trip latency
2: what is your replication byte rate

Also, you probably need to check the graphite metrics to figure out either consumer or producer is not fast enough

**Comment by soraka-hu** [comment]
HI:
   1.My TCP latency is：
![image](https://user-images.githubusercontent.com/72863256/96223184-14adbd00-0fc0-11eb-886d-5ca9403366a0.png)
    2.what is replication byte rate？ Where can I find it？
    3.how check the graphite metrics to figure?
You can write to me personally if it's convenient,Thank you very much.
   Email: 913337533@qq.com
  WeChat: huml_1005

**Comment by yangy0000** [comment]
1/ Please try to change "ling.ms" in producer configuration to 1000
2/ to check the byte rate, you would need to export uReplicator Worker metrics to graphite, but please try 1/ first.

**Comment by soraka-hu** [comment]
hi:
Thank you very mach for you reply.
1.I try to change "ling.ms"  in producer configuration to 1000,After a period of time, the speed will increase,for example:
    After I apply for a topic copy, the replication speed in the first five minutes is slower than that in the next five minutes
2.I want to check the byte rate,but i don't export uReplicator Worker metrics in graphite, Do you have any documentation or configuration or steps?

**Comment by yangy0000** [comment]
for 0.1 branch, worker metrics are export through jmx, there is an example in the user https://github.com/uber/uReplicator/wiki/uReplicator-User-Guide and the jmx configuration example: https://github.com/uber/uReplicator/blob/master/config/jmxtrans.xml
The metrics worth checking are
Consumer side: bytes-consumed-rateTotalBlockingQueueSize, ConsumerLag,MirrorMaker-flushLatencyMs,MirrorMaker-commitLatencyMs
Producer side: buffer-available-bytes, requests-in-flight,

**Comment by soraka-hu** [comment]
hi:
Thank you very mach for you reply.
1.I tried export uReplicator Worker metrics in graphite ,but i encounter a problem
![image](https://user-images.githubusercontent.com/72863256/97530482-35790800-19ed-11eb-810b-af483248a1c0.png)

My configuration is :
![image](https://user-images.githubusercontent.com/72863256/97530625-7bce6700-19ed-11eb-9f9f-9f7c7de8708e.png)
![image](https://user-images.githubusercontent.com/72863256/97530670-97d20880-19ed-11eb-8a7c-fc9d72cb03fa.png)
![image](https://user-images.githubusercontent.com/72863256/97530697-a4566100-19ed-11eb-9b1c-83ef2b41f9b9.png)

**Comment by soraka-hu** [comment]
hi:
  Thank you very mach , i try to install graphite,but this cannot be installed offline
  so i use master code and federation mode, at present, 3 worker ,3 controller,1 manager TPS arrive  230, 000/second.
 i will colse this issue
  Thank you very mach
