### ISSUE TITLE
Federation Mode ERROR:java heap space

### ISSUE THREAD

**Issue by soraka-hu** [uber/uReplicator#323]
hi:
 i have already published ureplicator federation mode online. but now, i get a log of error:

![微信图片_20201208214800](https://user-images.githubusercontent.com/72863256/101492437-d7522400-399f-11eb-93c2-7a0dbac42c06.png)
![微信图片_20201208214543](https://user-images.githubusercontent.com/72863256/101492449-d91be780-399f-11eb-965a-49a697cfbb1c.png)

This is my configuration:

![微信图片_20201208214627](https://user-images.githubusercontent.com/72863256/101492509-e6d16d00-399f-11eb-8115-d948bbb8d4cd.jpg)
![微信图片_20201208214633](https://user-images.githubusercontent.com/72863256/101492519-e8029a00-399f-11eb-8e17-174730577e0b.jpg)

I start worker using -Xmx=20g -Xms=20g, I think  it's enough to start that resource.but i don't no what happened?

@xhl1988  please help me.

**Comment by xhl1988** [comment]
How many partition and how much traffic does your worker handles?

**Comment by soraka-hu** [comment]
I have 18 partitions and 500000 traffic.

**Comment by yangy0000** [comment]
queued.max.message.chunks=1000 is a bit too big. 5-10 is generally enough

**Comment by soraka-hu** [comment]
ok,l already modify this setting,this problem has been solved.
   thank you very much. l prepare close this issue.
