### ISSUE TITLE
graphite metrics not working

### ISSUE THREAD

**Issue by shashankkoppar** [uber/uReplicator#331]
```
No available client connector supports the required protocols: 'WAR' . Please add the JAR of a matching connector to your classpath.
Starting the Jetty [HTTP/1.1] server on port 9000
Starting com.uber.stream.kafka.mirrormaker.controller.rest.ControllerRestApplication application
[2021-02-11 19:26:07,521] WARN Unable to report to Graphite (com.codahale.metrics.graphite.GraphiteReporter)
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:129)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:265)
[2021-02-11 19:27:07,517] WARN Unable to report to Graphite (com.codahale.metrics.graphite.GraphiteReporter)
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:129)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:265)
	controller.graphite.host : 35.187.124.7
	controller.graphite.port : 2003
	controller.graphite.report.freq.in.sec : 60
	controller.enable.graphite.report : true
	controller.graphite.host : 35.187.124.7
	controller.graphite.port : 2003
	controller.graphite.report.freq.in.sec : 60
	controller.enable.graphite.report : true
No available client connector supports the required protocols: 'WAR' . Please add the JAR of a matching connector to your classpath.
```

uber replicator is running fine, just metrics arent and i get this error. Can anyone let me know what jar file i should add to path?

**Comment by shashankkoppar** [comment]
@yangy0000 , would appreciate if u help out here :D 
```
Please add the JAR of a matching connector to your classpath.
```
which jar file should i add to classpath and how? 
https://javadoc.io/doc/io.dropwizard.metrics/metrics-graphite/latest/com/codahale/metrics/graphite/package-summary.html
 Is this jar file?

**Comment by yangy0000** [comment]
we didn't add any additional JAR into our classpath. 
which branch you are using?

**Comment by shashankkoppar** [comment]
I am using master branch

**Comment by shashankkoppar** [comment]
Can you also put an example for graphite metrics as well?
'''
      -graphiteHost {{ graphite_host }} \
      -metricsPrefix {{ helixClusterName }}-controller \
      -graphitePort 2003"
'''
It used to work before worker change you guys did 😄

**Comment by yangy0000** [comment]
Test metric at local, it is working,  the error "No available client connector" is irrelevant, I saw this error too.

The command I use in additional to the regular parameter is ` -graphitePort 2003  -graphiteHost localhost -metricsPrefix test-controller  -env dc1.zone1`
Metric start with prefix "stats.dc1.counter.test-controller.zone1"


From your error log "WARN Unable to report to Graphite (com.codahale.metrics.graphite.GraphiteReporter)
	at com.codahale.metrics.graphite.Graphite.connect(Graphite.java:129)
	at com.codahale.metrics.graphite.GraphiteReporter.report(GraphiteReporter.java:265)"
it looks like Graphite is not reachable

**Comment by shashankkoppar** [comment]
Thanks figured it out! :) path has changed! Before I didnt have to specify `stats.dc1.counter` now i have to! Will fix dashboards in my grafana!

**Comment by yangy0000** [comment]
great it worked, this change was part of the federated ureplicator release. sorry it breaks the backward compatibility

**Comment by shashankkoppar** [comment]
Thanks, @yangy0000 ! No worries! Also is it difficult to output Prometheus metrics instead?

**Comment by yangy0000** [comment]
it's not difficult but probably needs to touch many code. Alternatively, you should able to use https://github.com/prometheus/graphite_exporter to output Prometheus metrics
