### ISSUE TITLE
How to set the number of worker's threads, just like mirror maker's num_streams,num_producers?

### ISSUE THREAD

**Issue by yyb345** [uber/uReplicator#40]

**Comment by xhl1988** [comment]
You can specify num.consumer.fetchers=N in consumer.properties.
num.consumer.fetchers means max number of thread to consume from each broker.
For example, the partitions on one worker come from m brokers, the max number of CompactConsumerFetcherThread is N * m. https://github.com/uber/uReplicator/blob/master/uReplicator-Worker/src/main/scala/kafka/mirrormaker/CompactConsumerFetcherManager.scala#L113
