### ISSUE TITLE
Where is the start-controller-example1.sh file?

### ISSUE THREAD

**Issue by yunfan123** [uber/uReplicator#5]
I don't know how to start the controller.
And the project can't get compiled, because the default maven center don't have org.jacoco:jacoco-maven-plugin:jar:0.7.6-SNAPSHOT and org.restlet.ext.

**Comment by xhl1988** [comment]
Hi,

For org.jacoco, you can just remove this plugin since it’s a code coverage reporter and it’s not required.
For org.restlet.ext, please add the following in uMirrorMaker-Controller/pom.xml
```
<repositories>
    <repository>
        <id>maven-restlet</id>
        <name>Public online Restlet repository</name>
        <url>http://maven.restlet.org</url>
    </repository>
</repositories>
```
