### ISSUE TITLE
Not authorized by proxy

### ISSUE THREAD

**Issue by msiddiqi** [uber/uReplicator#97]
I keep getting the following when running mvn clean package.

I have tried specifying proxies for http, https, socks but all in vain using -D command line parameters. Anyone else getting this?

Could not resolve dependencies for project com.uber.uReplicator:uReplicator-Controller:jar:1.0.3-SNAPSHOT: Failed to collect dependencies at org.restlet.jse:org.restlet:jar:2.2.1: Failed to read artifact descriptor for org.restlet.jse:org.restlet:jar:2.2.1: Could not transfer artifact org.restlet.jse:org.restlet:pom:2.2.1 from/to maven-restlet (http://maven.restlet.org): Not authorized by proxy , ReasonPhrase:Proxy Authentication Required. -> [Help 1]

**Comment by xhl1988** [comment]
@msiddiqi  Have you solved this issue? I never experienced this before. Maybe check your setting.xml (https://stackoverflow.com/questions/5151345/maven-error-authorization-failed-not-authorized-by-proxy)
